'use client'
import { useState } from 'react'
import '../styles/globals.scss'


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [theme, setTheme] = useState('dark');


  return (
    <html lang="pl">
      <body className={`theme-${theme}`}>
        <header>
          <button onClick={() => {
            if(theme === 'dark') setTheme('light');
            else setTheme('dark')
          }}>Zmień motyw</button>
        </header>
        <main>{children}</main>
        <aside>Bok</aside>
        <footer>Stopka</footer>
      </body>
    </html>
  )
}
