import React from 'react'
import Icon from '@reacticons/ionicons';

import '../styles/globals.scss'
import '../styles/app.layout.scss'

export const metadata = {
  title: 'Laboratorium Sokolova',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  let theme = 'dark';

  return (
    <html lang="pl">
      <body className={`theme-${theme}`}>
        <div id="root">
          <header className="body-width">
            <nav>
              <ul>
                <li><a href="/"><Icon name='flask-sharp' /> Laboratorium</a></li>
                <li><a href="library"><Icon name='library-sharp' /> Biblioteka</a></li>
                <li><a href="authorization"><Icon name='library-sharp' /> Autoryzacja</a></li>
              </ul>
            </nav>
          </header>
          <main className="body-width">{children}</main>
          <footer>Stopka</footer>
        </div>
        <div id="background"></div>
      </body>
    </html>
  )
}
